name: idea_ushers_assignment
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  health: 8.1.0
  firebase_core: 2.24.2
  permission_handler: 11.0.1
  google_fonts: 6.1.0
  gap: 3.0.1
  shared_preferences: 2.2.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

