// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeof78TcWNb9Bo-0y1yuIqJALgg8M5kmE',
    appId: '1:982275785187:web:e430df2f6723b450d3a0d6',
    messagingSenderId: '982275785187',
    projectId: 'idea-ushers-assignment',
    authDomain: 'idea-ushers-assignment.firebaseapp.com',
    storageBucket: 'idea-ushers-assignment.appspot.com',
    measurementId: 'G-XKBN61WG44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPqc13_SvD8vNREkylNDnZqLxNpn8JTcI',
    appId: '1:982275785187:android:495a07a949f20773d3a0d6',
    messagingSenderId: '982275785187',
    projectId: 'idea-ushers-assignment',
    storageBucket: 'idea-ushers-assignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8sztXHnj24xBQJUuFsnQFrSVrWyNqFZU',
    appId: '1:982275785187:ios:614178977978d6b8d3a0d6',
    messagingSenderId: '982275785187',
    projectId: 'idea-ushers-assignment',
    storageBucket: 'idea-ushers-assignment.appspot.com',
    iosBundleId: 'com.example.ideaUshersAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8sztXHnj24xBQJUuFsnQFrSVrWyNqFZU',
    appId: '1:982275785187:ios:05ed2abdebca9637d3a0d6',
    messagingSenderId: '982275785187',
    projectId: 'idea-ushers-assignment',
    storageBucket: 'idea-ushers-assignment.appspot.com',
    iosBundleId: 'com.example.ideaUshersAssignment.RunnerTests',
  );
}
